version: '3.7'
services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=postgres
        ports: 
        - '5432:5432'
        volumes: 
        - ./pgdata:/var/lib/postgresql/data
    web:
      image: auth
      depends_on: 
        - db
      ports:
        - "4000:4000"


